// This is an autogenerated file from Firebase Studio.
import { initializeApp, getApps, getApp } from "firebase/app";
import { getFirestore, enableMultiTabIndexedDbPersistence } from "firebase/firestore";

// Your web app's Firebase configuration
// IMPORTANT: DO NOT COMMIT THIS FILE TO VERSION CONTROL
const firebaseConfig = {
  apiKey: "AIzaSyC-ZKdDLfdX2QT7rX0juOG6swVykHQC7Mw",
  authDomain: "panaderia-f82de.firebaseapp.com",
  projectId: "panaderia-f82de",
  storageBucket: "panaderia-f82de.firebasestorage.app",
  messagingSenderId: "740073694770",
  appId: "1:740073694770:web:93608330858093a22cbe2b"
};

// Initialize Firebase
const app = !getApps().length ? initializeApp(firebaseConfig) : getApp();
const db = getFirestore(app);

// Enable offline persistence
enableMultiTabIndexedDbPersistence(db).catch((err) => {
  if (err.code == 'failed-precondition') {
    // Multiple tabs open, persistence can only be enabled
    // in one tab at a time.
    console.log('Persistence failed, because multiple tabs are open.');
  } else if (err.code == 'unimplemented') {
    // The current browser does not support all of the
    // features required to enable persistence
     console.log('Persistence not available in this browser.');
  }
});


export { app, db };
